export const AGENTS = [
  {
    id:    'orchestrator',
    name:  'Content Orchestrator',
    role:  'Sprint Coordinator',
    color: 'purple',
    icon:  '🎯',
    tagline: 'Nothing moves without its sign-off.',
    goal: 'Coordinate the monthly creative sprint from start to finish. Brief every agent, monitor their output, retry failures, and deliver the final image catalog to the brand owner — on time, with nothing missing.',
    what_they_do: [
      { icon: '📋', title: 'Opens every sprint', text: 'Receives the brand inputs and kicks off the pipeline by briefing the Trend Scout and Content Strategist.' },
      { icon: '🔁', title: 'Monitors every step', text: 'Tracks each agent\'s output through a success-string check. Retries once on failure before escalating.' },
      { icon: '🚦', title: 'Gates the workflow', text: 'No agent starts work until the previous step is confirmed complete. Prevents cascading failures.' },
      { icon: '📦', title: 'Delivers the sprint', text: 'Collects the final catalog, sprint report, and calendar, then surfaces the package for brand owner review.' },
    ],
    skills: ['CrewAI orchestration', 'Delegation', 'Retry logic', 'Pipeline monitoring', 'Error escalation'],
    tasks: [
      { name: 'Open sprint',         description: 'Initialise the sprint with brand inputs and kick off the Trend Scout.' },
      { name: 'Delegate & monitor',  description: 'Pass briefs between agents and verify each step before advancing.' },
      { name: 'Handle failures',     description: 'Retry failed steps once with a corrected brief, then report the issue clearly.' },
      { name: 'Close sprint',        description: 'Collect final deliverables and present them to the brand owner for approval.' },
    ],
    workflow_position: 0,
    prev: null,
    next: 'trend_scout',
  },
  {
    id:    'trend_scout',
    name:  'Trend Scout',
    role:  'Instagram Trend Researcher',
    color: 'yellow',
    icon:  '🔍',
    tagline: 'Filters noise so the Strategist can focus on planning.',
    goal: 'Deliver one clean, structured trend brief to the Content Strategist every sprint — covering top trending formats, the top 5 hashtags in lifestyle and fashion, notable competitor moves, and any urgent time-sensitive opportunities.',
    what_they_do: [
      { icon: '📈', title: 'Tracks Instagram trends', text: 'Identifies top-performing content formats, rising aesthetics, and trending hashtags in the lifestyle and fashion space this week.' },
      { icon: '🏷️', title: 'Scores by relevance', text: 'Rates every trend — high, medium, or low relevance to The Lunchbags — so the Strategist knows what to act on immediately.' },
      { icon: '👀', title: 'Watches competitors', text: 'Monitors competitor accounts and flags any notable moves: new campaigns, formats, or positioning shifts.' },
      { icon: '🚨', title: 'Flags urgencies', text: 'Surfaces anything time-sensitive — seasonal moments, viral formats, trending sounds — at the top of every brief.' },
    ],
    skills: ['Trend analysis', 'Instagram research', 'Competitor monitoring', 'Relevance scoring', 'Hashtag research'],
    tasks: [
      { name: 'Research trends',     description: 'Scan Instagram for top-performing formats and hashtags in lifestyle and fashion this sprint.' },
      { name: 'Score relevance',     description: 'Rate each trend high / medium / low for The Lunchbags brand.' },
      { name: 'Monitor competitors', description: 'Review competitor accounts for new campaigns or notable moves.' },
      { name: 'Deliver trend brief', description: 'Write a structured, scored brief — never raw data — for the Content Strategist.' },
    ],
    workflow_position: 1,
    prev: 'orchestrator',
    next: 'strategist',
  },
  {
    id:    'strategist',
    name:  'Content Strategist',
    role:  'Creative Brief Writer',
    color: 'blue',
    icon:  '📋',
    tagline: 'Every brief is specific enough to execute without a follow-up question.',
    goal: 'Read the reference images and campaign concept for this sprint, extract their visual world precisely, and write a creative brief that gives the Visual Director everything needed to recreate that world with The Lunchbags product.',
    what_they_do: [
      { icon: '🖼️', title: 'Reads the references', text: 'Calls the Style Reference and Composition Reader tools to extract setting, lighting, props, mood, and composition style from every moodboard image.' },
      { icon: '📖', title: 'Reads the concept', text: 'Checks concept.md for any campaign narrative. Blends the narrative direction with the visual world from the references — neither overrides the other.' },
      { icon: '✍️', title: 'Writes the brief', text: 'Produces a per-image breakdown of setting, lighting, subject, props, mood, and composition — precise enough for the Director to execute without asking a follow-up.' },
      { icon: '🗓️', title: 'Plans the shot mix', text: 'Derives shot distribution from what the references actually show — no inventing settings or formats not present in the moodboard.' },
    ],
    skills: ['Visual analysis', 'Creative briefing', 'Reference extraction', 'Content strategy', 'Shot planning'],
    tasks: [
      { name: 'Read campaign concept',  description: 'Call ConceptReaderTool to load the narrative direction for this sprint.' },
      { name: 'Read reference images',  description: 'Call StyleReferenceReaderTool and CompositionReaderTool on all images in references/.' },
      { name: 'Write creative brief',   description: 'Describe each ref\'s setting, lighting, subject, props, mood, and composition precisely.' },
      { name: 'Define shot mix',        description: 'Set the distribution of shot types based strictly on what the references show.' },
    ],
    workflow_position: 2,
    prev: 'trend_scout',
    next: 'director',
  },
  {
    id:    'director',
    name:  'Visual Director',
    role:  'Art Director',
    color: 'pink',
    icon:  '🎨',
    tagline: 'Every image feels like it came from the same session, same photographer, same light.',
    goal: 'Recreate the world of the reference images with The Lunchbags product. Design 3 shoot sets, write a DNA Prompt Block for each that locks the lighting and aesthetic, then write a Shot List of 50 compositions — specifying product variant, model presence, angle, and subject distance for every single frame.',
    what_they_do: [
      { icon: '🏗️', title: 'Designs shoot sets', text: 'Defines 3 complete sets — each with its own location, lighting setup, props, and energy — that match the world shown in the reference images.' },
      { icon: '🧬', title: 'Writes DNA blocks', text: 'Creates a DNA Prompt Block per set: a locked specification of lighting, lens, colours, and mood that keeps all images in that set visually cohesive.' },
      { icon: '📷', title: 'Writes the shot list', text: 'Writes every composition in the Sprint — product variant, model presence, angle (eye / high / low), subject distance (wide / mid / close / macro) — for all 50 frames.' },
      { icon: '⚖️', title: 'Reviews all 3 sets', text: 'Before submitting, reviews all three DNA blocks side-by-side to ensure equal depth and creative quality. Set 3 is never an afterthought.' },
    ],
    skills: ['Art direction', 'Composition design', 'Lighting specification', 'Shot list writing', 'Visual consistency'],
    tasks: [
      { name: 'Design 3 shoot sets',  description: 'Define location, lighting, props, and energy for each set based on the references.' },
      { name: 'Write DNA blocks',     description: 'Produce one locked DNA Prompt Block per set used by the Photographer for every image in that set.' },
      { name: 'Write shot list',      description: 'Specify all 50 shots: product variant, model, angle, distance, and composition notes.' },
      { name: 'Quality gate review',  description: 'Review all 3 DNA blocks side-by-side before submitting — confirm equal depth and quality.' },
    ],
    workflow_position: 3,
    prev: 'strategist',
    next: 'photographer',
  },
  {
    id:    'photographer',
    name:  'Photographer',
    role:  'Image Generator',
    color: 'orange',
    icon:  '📸',
    tagline: 'Executes the entire shoot in one flow to maintain artistic momentum.',
    goal: 'Read the Style Bible, DNA blocks, and Shot List. Generate all 50 images in one continuous run using multimodal prompts that combine product reference images, style references, and the DNA block for each set. Deliver a complete, high-fidelity image catalog ready for Photo Editor review.',
    what_they_do: [
      { icon: '🖼️', title: 'Builds multimodal prompts', text: 'Combines product reference images, style reference images, and the DNA Prompt Block for each set into a single rich prompt for every shot.' },
      { icon: '⚡', title: 'Runs 3 parallel workers', text: 'Generates images 3 at a time using concurrent workers — roughly 3× faster than sequential generation, with thread-safe quota detection.' },
      { icon: '🚫', title: 'Enforces hard constraints', text: 'Injects hard rules at the top of every prompt — no shoulder strap, exact pattern match, correct bag scale — before any style reference is applied.' },
      { icon: '🔄', title: 'Retries intelligently', text: 'Up to 3 attempts per shot with style refs, then one fallback attempt without refs. Skips remaining shots if the daily quota is exhausted.' },
    ],
    skills: ['Gemini image generation', 'Multimodal prompting', 'Parallel processing', 'Asset management', 'Film processing'],
    tasks: [
      { name: 'Generate all 50 images',  description: 'Execute the full shot list in one run — product refs + style refs + DNA block per image.' },
      { name: 'Apply film processing',   description: 'Run FilmProcessorTool on every generated image for consistent colour and tone across the batch.' },
      { name: 'Write captions',          description: 'Run CopywriterTool to produce Greek Instagram captions and hashtags for all approved images.' },
      { name: 'Build posting calendar',  description: 'Run ContentPlannerTool to schedule images across the brand\'s 5 posts/week cadence.' },
    ],
    workflow_position: 4,
    prev: 'director',
    next: 'photo_editor',
  },
  {
    id:    'photo_editor',
    name:  'Photo Editor',
    role:  'QC Reviewer & Fixer',
    color: 'green',
    icon:  '🔎',
    tagline: 'The final gatekeeper before the campaign reaches the brand owner.',
    goal: 'Review every generated image against the product references. Approve clean images, apply targeted fixes for minor issues, and flag structural failures for full regeneration — ensuring the final image library is accurate, consistent, and brand-ready.',
    what_they_do: [
      { icon: '✅', title: 'Approves clean images', text: 'First-pass approval for images that match the product reference on pattern, shape, scale, and model consistency.' },
      { icon: '🛠️', title: 'Fixes minor issues', text: 'For small problems — wrong label text, colour shift, minor prop detail — applies up to 3 targeted inpainting corrections.' },
      { icon: '🚨', title: 'Flags structural failures', text: 'Detects shoulder straps, wrong bag shapes, and wrong scale — issues inpainting cannot fix. Marks these as Regen- for full regeneration instead of wasting fix attempts.' },
      { icon: '💾', title: 'Checkpoints after every image', text: 'Saves progress to disk after each review. If the process disconnects mid-set, it resumes exactly from where it stopped — no images are re-reviewed.' },
    ],
    skills: ['Image quality control', 'Inpainting / fixing', 'Structural failure detection', 'Batch consistency checking', 'Checkpoint management'],
    tasks: [
      { name: 'Review every image',         description: 'Compare each frame against product references — pattern, shape, scale, model, and composition.' },
      { name: 'Apply targeted fixes',        description: 'Use inpainting to correct minor issues in up to 3 attempts per image.' },
      { name: 'Detect structural failures',  description: 'Identify shoulder straps, wrong models, and wrong scale — mark as Regen- and skip fix attempts.' },
      { name: 'Run batch consistency check', description: 'After reviewing all images in a set, flag any that drift from the technical spec in colour temperature or shadow quality.' },
    ],
    workflow_position: 5,
    prev: 'photographer',
    next: null,
  },
]

export const AGENT_MAP = Object.fromEntries(AGENTS.map(a => [a.id, a]))

export const COLOR_CLASSES = {
  purple: { bg: 'bg-purple-500/10', text: 'text-purple-400', border: 'border-purple-500/20', badge: 'bg-purple-500/20 text-purple-300', dot: 'bg-purple-400' },
  yellow: { bg: 'bg-yellow-500/10', text: 'text-yellow-400', border: 'border-yellow-500/20', badge: 'bg-yellow-500/20 text-yellow-300', dot: 'bg-yellow-400' },
  blue:   { bg: 'bg-blue-500/10',   text: 'text-blue-400',   border: 'border-blue-500/20',   badge: 'bg-blue-500/20 text-blue-300',   dot: 'bg-blue-400'   },
  pink:   { bg: 'bg-pink-500/10',   text: 'text-pink-400',   border: 'border-pink-500/20',   badge: 'bg-pink-500/20 text-pink-300',   dot: 'bg-pink-400'   },
  orange: { bg: 'bg-orange-500/10', text: 'text-orange-400', border: 'border-orange-500/20', badge: 'bg-orange-500/20 text-orange-300', dot: 'bg-orange-400' },
  green:  { bg: 'bg-green-500/10',  text: 'text-green-400',  border: 'border-green-500/20',  badge: 'bg-green-500/20 text-green-300',  dot: 'bg-green-400'  },
}
